"""add invoice_counter table

Revision ID: baf6022659f2
Revises: d7b6b089c3b5
Create Date: 2026-07-26 20:50:48.210584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf6022659f2'
down_revision: Union[str, Sequence[str], None] = 'd7b6b089c3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("INSERT INTO invoice_counter (id, count) VALUES (1, 0)")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM invoice_counter WHERE id = 1")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_counter')
    # ### end Alembic commands ###
